package presentation;

import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sabio.SABioException;
import sabio.SABioFactory;
import sabio.spec.IUsuario;
import vo.UsuarioVO;

public class LoginView extends javax.swing.JFrame {

    private static LoginView loginview;
    private UsuarioVO usuarioLogado;
    private ResourceBundle bundle;

    public LoginView() {
        super("Login");
        initComponents();
        this.setVisible(true);
    }

    public static LoginView getInstance() {
        if (loginview == null) {
            loginview = new LoginView();
        }
        return loginview;
    }

    public static void destroyInstance() {
        loginview = null;
    }
    
    public void authenticateUser(UsuarioVO usuario) {
        IUsuario user = SABioFactory.getInstance().getUsuario();
        try {
            if (user.authenticate(usuario)) {
                this.usuarioLogado = user.getUsuarioByLogin(usuario.getLogin());
            } else {
                this.usuarioLogado = null;
            }

        } catch (SABioException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_login = new javax.swing.JTextField();
        botao_login = new javax.swing.JButton();
        botao_cadastrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        campo_senha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("presentation/Bundle_pt_BR"); // NOI18N
        jLabel1.setText(bundle.getString("LoginView.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("LoginView.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText(bundle.getString("LoginView.jLabel3.text")); // NOI18N

        campo_login.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        campo_login.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        botao_login.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botao_login.setText(bundle.getString("LoginView.botao_login.text")); // NOI18N
        botao_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_loginActionPerformed(evt);
            }
        });

        botao_cadastrar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botao_cadastrar.setText(bundle.getString("LoginView.botao_cadastrar.text")); // NOI18N
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });

        campo_senha.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel4.setText(bundle.getString("LoginView.jLabel4.text")); // NOI18N

        buttonGroup1.add(jRadioButton1);
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("presentation/Bundle"); // NOI18N
        jRadioButton1.setText(bundle1.getString("LoginView.jRadioButton1.text")); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(bundle1.getString("LoginView.jRadioButton3.text")); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 177, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao_cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(botao_login))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campo_login, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campo_senha)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cadastrar)
                    .addComponent(botao_login))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_loginActionPerformed
        try {
            String login = campo_login.getText();
            String senha = String.copyValueOf(campo_senha.getPassword());

            boolean autenticado = false;
            IUsuario user = SABioFactory.getInstance().getUsuario();
            UsuarioVO vo = new UsuarioVO(login, senha);

            try {
                autenticado = user.authenticate(vo);
            } catch (Exception e) {
                autenticado = false;
            }

            if (autenticado) {
                this.setVisible(false);
                AtendenteView.getInstance().setFocusableWindowState(true);
                destroyInstance();
            } else {
                
            Locale locale = Locale.getDefault();
            
            if (locale.getLanguage().equals("pt"))
            {
                JOptionPane.showMessageDialog(null,"Senha ou Login Incorreto", "Erro!", JOptionPane.WARNING_MESSAGE);
                campo_login.setText("");
                campo_senha.setText("");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Wrong Login or Password", "Error!", JOptionPane.WARNING_MESSAGE);
                campo_login.setText("");
                campo_senha.setText("");
            }
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_botao_loginActionPerformed

    private void atualiza(){
            jLabel1.setText(bundle.getString("LoginView.jLabel1.text")); // NOI18N
            jLabel2.setText(bundle.getString("LoginView.jLabel2.text"));
            jLabel3.setText(bundle.getString("LoginView.jLabel3.text"));
            botao_cadastrar.setText(bundle.getString("LoginView.botao_cadastrar.text"));
            botao_login.setText(bundle.getString("LoginView.botao_login.text")); // NOI18N
            
            this.validate();
            this.repaint();
          
    }
    
    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed
        
        String login = campo_login.getText();
        String senha = String.copyValueOf(campo_senha.getPassword());
    
        SABioFactory factory = SABioFactory.getInstance();
        UsuarioVO user = new UsuarioVO(); 
        user.setLogin(login);
        user.setSenha(senha);
        
        try {
            factory.getUsuario().create(user);
            campo_login.setText("");
            campo_senha.setText("");
        } catch (SABioException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_botao_cadastrarActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        Locale locale = new Locale("en", "US");
        Locale.setDefault(locale);
        JOptionPane.showMessageDialog(null, "Language Changed", "Success!", JOptionPane.INFORMATION_MESSAGE);
        bundle = ResourceBundle.getBundle("I18n/Bundle");
  
        atualiza();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Locale locale = new Locale("pt", "BR");
        Locale.setDefault(locale);
        JOptionPane.showMessageDialog(null, "Idioma Alterado", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        bundle = ResourceBundle.getBundle("I18n/Bundle");
        atualiza();    
}//GEN-LAST:event_jRadioButton1ActionPerformed
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_login;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campo_login;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}

