package presentation;

import java.util.logging.Level;
import java.util.logging.Logger;
import sabio.SABioException;
import sabio.SABioFactory;
import sabio.spec.IUsuario;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import vo.UsuarioVO;

public class LoginView extends javax.swing.JFrame {

    private static LoginView loginview;
    private UsuarioVO usuarioLogado;

    public LoginView() {
        super("Login");
        initComponents();
        this.setVisible(true);
        
    }

    public static LoginView getInstance() {
        if (loginview == null) {
            loginview = new LoginView();
        }
        return loginview;
    }

    public static void destroyInstance() {
        loginview = null;
    }
    
    public void authenticateUser(UsuarioVO usuario) {
        IUsuario user = SABioFactory.getInstance().getUsuario();
        try {
            if (user.authenticate(usuario)) {
                this.usuarioLogado = user.getUsuarioByLogin(usuario.getLogin());
            } else {
                this.usuarioLogado = null;
            }

        } catch (SABioException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_login = new javax.swing.JTextField();
        botao_login = new javax.swing.JButton();
        botao_cadastrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        campo_senha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("presentation/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("LoginView.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("LoginView.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText(bundle.getString("LoginView.jLabel3.text")); // NOI18N

        campo_login.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        campo_login.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botao_login.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botao_login.setText(bundle.getString("LoginView.botao_login.text")); // NOI18N
        botao_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_loginActionPerformed(evt);
            }
        });

        botao_cadastrar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        botao_cadastrar.setText(bundle.getString("LoginView.botao_cadastrar.text")); // NOI18N
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });

        campo_senha.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel4.setText(bundle.getString("LoginView.jLabel4.text")); // NOI18N

        jComboBox2.setMaximumRowCount(1);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Português", "Inglês" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botao_cadastrar)
                            .addGap(18, 18, 18)
                            .addComponent(botao_login))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_login, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_senha))))
                    .addGap(69, 69, 69))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2))
                    .addContainerGap()))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cadastrar)
                    .addComponent(botao_login))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        Locale locale = new Locale("en", "US");
        Locale.setDefault(locale);
        JOptionPane.showMessageDialog(null,"Language Changed", "Success!", JOptionPane.INFORMATION_MESSAGE);
        atualiza();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void botao_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_loginActionPerformed
        try {
            String login = campo_login.getText();
            String senha = String.copyValueOf(campo_senha.getPassword());

            boolean autenticado = false;
            IUsuario user = SABioFactory.getInstance().getUsuario();
            UsuarioVO vo = new UsuarioVO(login, senha);

            try {
                autenticado = user.authenticate(vo);
            } catch (Exception e) {
                autenticado = false;
            }

            if (autenticado) {
                destroyInstance();
                AtendenteView atendente = new AtendenteView();
            } else {
                destroyInstance();
                AtendenteView atendente = new AtendenteView();
                /*
                JOptionPane.showMessageDialog(LoginView.getInstance(),
                        bundle.getString("JPLogin.Messages.LoginError"),
                        bundle.getString("JPLogin.Messages.LoginError.Title"),
                        JOptionPane.WARNING_MESSAGE);
                        * 
                        */
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_botao_loginActionPerformed

    private void atualiza(){
            java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("View/Bundle");
            jLabel1.setText(bundle.getString("LoginView.jLabel1.text")); // NOI18N
            jLabel2.setText(bundle.getString("LoginView.jLabel2.text"));
            jLabel3.setText(bundle.getString("LoginView.jLabel3.text"));
            botao_cadastrar.setText(bundle.getString("LoginView.botao_cadastrar.text"));
            botao_login.setText(bundle.getString("LoginView.botao_login.text")); // NOI18N
            
            this.validate();
            this.repaint();
          
    }
    
    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed
        
        String login = campo_login.getText();
        String senha = String.copyValueOf(campo_senha.getPassword());
    
        SABioFactory factory = SABioFactory.getInstance();
        UsuarioVO user = new UsuarioVO(); 
        user.setLogin(login);
        user.setSenha(senha);
        
        try {
            factory.getUsuario().create(user);
        } catch (SABioException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_botao_cadastrarActionPerformed
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }
    
    private void updateComponents(){
            java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("View/Bundle");
            jLabel1.setText(bundle.getString("LoginView.jLabel1.text")); // NOI18N
            jLabel2.setText(bundle.getString("LoginView.jLabel2.text"));
            jLabel3.setText(bundle.getString("LoginView.jLabel3.text"));
            botao_cadastrar.setText(bundle.getString("LoginView.botao_cadastrar.text"));
            botao_login.setText(bundle.getString("LoginView.botao_login.text")); // NOI18N
            
            this.validate();
            this.repaint();
          
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_login;
    private javax.swing.JTextField campo_login;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
